openapi: 3.1.0
info:
    version: 1.0.0
    title: API documentaion
    description: Theneo Node API documentaion.
    contact:
        email: giorgi199817@gmail.com
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
schemes: [http, https]
servers:
  - url: http://localhost:4000/api
paths:
    $ref: ./paths/index.yaml
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid
    schemas:
        User:
            $ref: ./definitions/models/User.yaml
        Note:
            $ref: ./definitions/models/Note.yaml
        Category:
            $ref: ./definitions/models/Category.yaml
        UserMatched:
            $ref: ./definitions/models/UserMatched.yaml